services:
  backend:
    image: evslopes7/maedaprole-backend
    build:
      context: ../maedaprole-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mae_da_prole_dev
      - SPRING_DATASOURCE_USERNAME=jhhdev
      - SPRING_DATASOURCE_PASSWORD=dev_2025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_MAIL_HOST=sandbox.smtp.mailtrap.io # Configurações de e-mail de teste
      - SPRING_MAIL_PORT=2525
      - SPRING_MAIL_USERNAME=ce4a1c36bb9d78
      - SPRING_MAIL_PASSWORD=b233532058b492
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
    depends_on:
      - postgres
    networks:
      - maedaprole_network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mae_da_prole_dev
      POSTGRES_USER: jhhdev
      POSTGRES_PASSWORD: dev_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - maedaprole_network

  strapi:
    image: evslopes7/maedaprole-cms
    build:
      context: ../maedaprole-cms
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: mae_da_prole_dev
      DATABASE_USERNAME: jhhdev
      DATABASE_PASSWORD: dev_2025
      NODE_ENV: development
      HOST: 0.0.0.0
      APP_KEYS: "1EmfuUuBnim9K/S6kNask6oPeCKc3S5cY5du7YBCl+A=,4C1Tp1jj3urYBMJb+ziqge/i7RQCc6u9Ef7ZjOGlApg=,gdnQ4ifN72w2eAF6Md2Sm1WoCSpoGGHbm+EKZin0AGY=,jK1lxzKgU7dCzw3d+VEqF+OsPpGQIm/qI5MvMdQL/Ag="
      API_TOKEN_SALT: 1EmfuUuBnim9K/S6kNask6oPeCKc3S5cY5du7YBCl+A=
      ADMIN_JWT_SECRET: 4C1Tp1jj3urYBMJb+ziqge/i7RQCc6u9Ef7ZjOGlApg=
      JWT_SECRET: gdnQ4ifN72w2eAF6Md2Sm1WoCSpoGGHbm+EKZin0AGY=

    volumes:
      - ../maedaprole-cms/config:/srv/app/config  # <-- Caminhos corretos (v4)
      - ../maedaprole-cms/public/uploads:/srv/app/public/uploads
      - ../maedaprole-cms/data:/srv/app/data
      - ../maedaprole-cms/src:/srv/app/src #Para hot reload
    depends_on:
      - postgres
    networks:
      - maedaprole_network

  frontend:
    image: evslopes7/maedaprole-frontend
    build:
      context: ../maedaprole-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ../maedaprole-frontend:/app
    depends_on:
      - backend
      - strapi
    networks:
      - maedaprole_network

volumes:
  postgres_data:
    name: "maedaprole_dbdata"

networks:
  maedaprole_network:
    name: "maedaprole_network"