name: Infra CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout infra code
      uses: actions/checkout@v3

    - name: Checkout backend code
      uses: actions/checkout@v3
      with:
        repository: evslopes/maedaprole-backend
        path: ../maedaprole-backend

    - name: Checkout frontend code
      uses: actions/checkout@v3
      with:
        repository: evslopes/maedaprole-frontend
        path: ../maedaprole-frontend

    - name: Checkout CMS code
      uses: actions/checkout@v3
      with:
        repository: evslopes/maedaprole-cms
        path: ../maedaprole-cms

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Use Docker with Docker Compose
      uses: docker://docker/compose:1.29.2

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push        DOCKER_BUILDKIT=1 docker-compose build --progress=plain
        docker-compose push