name: Infra CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:  # Um único job por enquanto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v4

      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-backend
          path: maedaprole-backend  # Caminho relativo, SEM ../
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout Frontend Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-frontend
          path: maedaprole-frontend  # Caminho relativo, SEM ../
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout CMS Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-cms
          path: maedaprole-cms  # Caminho relativo, SEM ../
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub  # Opcional, se for fazer push
        if: github.ref == 'refs/heads/main'  # Só na main
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker compose build  # Executa na raiz do repositório de infra
          # docker compose push    # Descomente se for fazer push