name: Infra CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra code
        uses: actions/checkout@v4

      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-backend
          path: maedaprole-infra/maedaprole-backend
          token: ${{ secrets.GH_TOKEN }}

      - name: List backend directory
        run: ls -R maedaprole-infra/maedaprole-backend

      - name: Checkout frontend code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-frontend
          path: maedaprole-infra/maedaprole-frontend
          token: ${{ secrets.GH_TOKEN }}

      - name: List frontend directory
        run: ls -R maedaprole-infra/maedaprole-frontend

      - name: Checkout CMS code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-cms
          path: maedaprole-infra/maedaprole-cms
          token: ${{ secrets.GH_TOKEN }}

      - name: List CMS directory
        run: ls -R maedaprole-infra/maedaprole-cms

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and push Docker images
        run: |
          cd maedaprole-infra
          docker compose build
          docker compose push