name: Infra CI/CD

on:
  push:
    branches:
      - main  # Executa em pushes na main (ou na sua branch principal)
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:  # Nome do job (você pode ter vários jobs, ex: build, test, deploy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra code
        uses: actions/checkout@v4  # Checkout do repositório de INFRAESTRUTURA

      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-backend
          path: maedaprole-backend  #  <--  Diretório relativo à raiz do repositório de infra
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout frontend code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-frontend
          path: maedaprole-frontend  # <--  Diretório relativo
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout CMS code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-cms
          path: maedaprole-cms  # <--  Diretório relativo
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx  # <--  Use a versão mais recente
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub  # Só se for fazer push
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          cd maedaprole-backend  # <--  Entra na pasta do back-end
          docker compose build
          docker compose push  
