name: Infra CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v4

      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-backend
          path: ../maedaprole-backend
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout Frontend Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-frontend
          path: ../maedaprole-frontend
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout CMS Code
        uses: actions/checkout@v4
        with:
          repository: evslopes/maedaprole-cms
          path: ../maedaprole-cms
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub  # Somente se for fazer push
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker compose build  # Executa o build a partir da raiz do repositório de infra
          # docker compose push   # Descomente para fazer push (após o build)

    # Exemplo de como adicionar o deploy no Heroku DEPOIS que o build funcionar.
    # (Opcional) Deploy no Heroku (backend)
    #- name: Deploy to Heroku (backend)
    #  uses: akhileshns/heroku-deploy@v3.12.14
    #  with:
    #    heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #    heroku_app_name: "seu-app-backend"  # Substitua
    #    heroku_email: "[email protected]"
    #    appdir: "../maedaprole-backend"

    #Exemplo de deploy do Strapi no Heroku (usando o Heroku Container Registry)
    #- name: Deploy Strapi CMS to Heroku
    #  run: |
    #      cd ../maedaprole-cms
    #      heroku container:login
    #      heroku container:push web -a <nome-do-seu-app-strapi-no-heroku>
    #      heroku container:release web -a <nome-do-seu-app-strapi-no-heroku>